In [59]:
import bagpy
import pandas as pd
import sys
import numpy as np
import os
from scipy.spatial.transform import Rotation as R

file_path = '/home/shc/Desktop/data/1026/phacon_segm_depth_2.bag'
b = bagpy.bagreader(file_path)
b.topic_table

[INFO]  Data folder /home/shc/Desktop/data/1026/phacon_segm_depth_2 already exists. Not creating.


Topics                        Types  Message Count  \
0          /fwd_depthData      sensor_msgs/PointCloud2            956   
1  /fwd_limage/compressed  sensor_msgs/CompressedImage            956   
2       /fwd_pose_camhand    geometry_msgs/PoseStamped            956   
3         /fwd_pose_drill    geometry_msgs/PoseStamped            956   
4           /fwd_pose_pan    geometry_msgs/PoseStamped            956   
5  /fwd_rimage/compressed  sensor_msgs/CompressedImage            957   
6    /fwd_segm/compressed  sensor_msgs/CompressedImage            956   

   Frequency  
0  13.100322  
1  13.057459  
2  13.050228  
3  13.065513  
4  13.057622  
5  13.075716  
6  13.055549

In [60]:
pose_cam_data = b.message_by_topic('/fwd_pose_camhand')
pose_pan_data = b.message_by_topic('/fwd_pose_pan')

df_pan = pd.read_csv(pose_pan_data)
df_cam_hand = pd.read_csv(pose_cam_data)

In [61]:
os.chdir('/home/shc/RoboMaster/util')
from Solver import solver
from dataLoader import dataLoader
sol = solver()
ld = dataLoader()

phacon2pan = np.load('/home/shc/RoboMaster/params/phacon2pan_1028.npy')
# pan2phacon = np.load('/home/shc/RoboMaster/params/phacon2pan.npy')

X = np.load("/home/shc/Desktop/data/1023/handeye_1/hand_eye_X.npy")

In [62]:
def getRealPose(idx, pd_data):
    df = pd_data
    pose_x = df['pose.position.x'][idx]*1000
    pose_y = df['pose.position.y'][idx]*1000
    pose_z = df['pose.position.z'][idx]*1000
    orin_x = df['pose.orientation.x'][idx]
    orin_y = df['pose.orientation.y'][idx]
    orin_z = df['pose.orientation.z'][idx]
    orin_w = df['pose.orientation.w'][idx]
    pose = np.array([pose_x, pose_y, pose_z, orin_x, orin_y, orin_z, orin_w])
    # print(real_pose, '\n', pose)
    return pose

In [63]:
num_frames = len(df_cam_hand)
pose_pan_data = np.zeros([num_frames, 4, 4])
pose_camhand_data = np.zeros([num_frames, 4, 4])
for i in range(num_frames):
    quaternion_pan = getRealPose(i, df_pan)
    quaternion_camhand = getRealPose(i, df_cam_hand)
    _, op2pan = sol.seven2trans(quaternion_pan)
    _, op2camhand = sol.seven2trans(quaternion_camhand)
    
    pan2phacon = sol.invTransformation(phacon2pan)
    op2phacon = op2pan@pan2phacon
    op2cam = op2camhand@X
     ## F_cv_ambf, cam2ambf
    extrinsic = np.array([[0, 1, 0, 0], [0, 0, -1, 0],
                          [-1, 0, 0, 0], [0, 0, 0, 1]])
    # op2cam = op2cam@extrinsic
    cam2phacon = sol.invTransformation(op2cam)@op2phacon
print(cam2phacon)
# r = R.from_matrix(cam2phacon[:3,:3])
# r.as_euler('xyz', degrees=True)


[[-6.18818184e-01  4.49837497e-01  6.43980032e-01 -4.22822921e+01]
 [ 3.61652843e-01  8.90896212e-01 -2.74792941e-01  1.39347535e+01]
 [-6.97331540e-01  6.28503409e-02 -7.13987786e-01  1.49692417e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [64]:
ambf2phacon = sol.invTransformation(extrinsic)@cam2phacon

In [65]:
t = ambf2phacon[:3, 3]/0.194/1000
r = R.from_matrix(ambf2phacon[:3,:3])
Rot = r.as_euler('xyz')
# Rot = Rot@Rot_offset
print('position: {{x: {0}, y: {1}, z: {2}}}'.format(t[0],t[1],t[2]))
print('orientation: {{r: {0}, p: {1}, y: {2}}}'.format(Rot[0], Rot[1], Rot[2]))

position: {x: -0.7716103963912765, y: -0.21794995904842976, z: -0.0718286262388144}
orientation: {r: -1.2716094761176961, p: 0.3700401267868294, y: -0.7258149555080722}


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