In [21]:
import bagpy
import pandas as pd
import sys
import numpy as np
import os
from scipy.spatial.transform import Rotation as R

file_path = '/home/shc/Desktop/data/1026/phacon_pose_2.bag'
b = bagpy.bagreader(file_path)
b.topic_table

[INFO]  Data folder /home/shc/Desktop/data/1026/phacon_pose_2 already exists. Not creating.


Topics                        Types  Message Count  \
0  /fwd_limage/compressed  sensor_msgs/CompressedImage            109   
1       /fwd_pose_camhand    geometry_msgs/PoseStamped            109   
2         /fwd_pose_drill    geometry_msgs/PoseStamped            110   
3           /fwd_pose_pan    geometry_msgs/PoseStamped            109   
4  /fwd_rimage/compressed  sensor_msgs/CompressedImage            109   

   Frequency  
0  29.920098  
1  29.920845  
2  29.932162  
3  29.926929  
4  29.893335

In [22]:
pose_cam_data = b.message_by_topic('/fwd_pose_camhand')
pose_pan_data = b.message_by_topic('/fwd_pose_pan')

df_pan = pd.read_csv(pose_pan_data)
df_cam_hand = pd.read_csv(pose_cam_data)

In [23]:
os.chdir('/home/shc/RoboMaster/util')
from Solver import solver
from dataLoader import dataLoader
sol = solver()
ld = dataLoader()

phacon2pan = np.load('/home/shc/RoboMaster/params/phacon2pan.npy')
# pan2phacon = np.load('/home/shc/RoboMaster/params/phacon2pan.npy')

X = np.load("/home/shc/Desktop/data/1023/handeye_1/hand_eye_X.npy")

In [24]:
def getRealPose(idx, pd_data):
    df = pd_data
    pose_x = df['pose.position.x'][idx]*1000
    pose_y = df['pose.position.y'][idx]*1000
    pose_z = df['pose.position.z'][idx]*1000
    orin_x = df['pose.orientation.x'][idx]
    orin_y = df['pose.orientation.y'][idx]
    orin_z = df['pose.orientation.z'][idx]
    orin_w = df['pose.orientation.w'][idx]
    pose = np.array([pose_x, pose_y, pose_z, orin_x, orin_y, orin_z, orin_w])
    # print(real_pose, '\n', pose)
    return pose

In [25]:
num_frames = len(df_cam_hand)
pose_pan_data = np.zeros([num_frames, 4, 4])
pose_camhand_data = np.zeros([num_frames, 4, 4])
for i in range(num_frames):
    quaternion_pan = getRealPose(i, df_pan)
    quaternion_camhand = getRealPose(i, df_cam_hand)
    _, op2pan = sol.seven2trans(quaternion_pan)
    _, op2camhand = sol.seven2trans(quaternion_camhand)
    
    pan2phacon = sol.invTransformation(phacon2pan)
    op2phacon = op2pan@pan2phacon
    op2cam = op2camhand@X
     ## F_cv_ambf, cam2ambf
    extrinsic = np.array([[0, 1, 0, 0], [0, 0, -1, 0],
                          [-1, 0, 0, 0], [0, 0, 0, 1]])
    # op2cam = op2cam@extrinsic
    cam2phacon = sol.invTransformation(op2cam)@op2phacon
print(cam2phacon)
# r = R.from_matrix(cam2phacon[:3,:3])
# r.as_euler('xyz', degrees=True)


[[ 6.05654759e-01 -2.27992481e-03 -7.95724271e-01  3.66872049e+00]
 [-3.93326423e-01  8.68431261e-01 -3.01863330e-01  3.28103065e+00]
 [ 6.91720058e-01  4.95804343e-01  5.25072772e-01  1.45178795e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [26]:
ambf2phacon = sol.invTransformation(extrinsic)@cam2phacon

In [27]:
t = ambf2phacon[:3, 3]/0.194/1000
r = R.from_matrix(ambf2phacon[:3,:3])
Rot = r.as_euler('xyz')
# Rot = Rot@Rot_offset
print('t:', t)
print('R:', Rot)

t: [-0.7483443   0.01891093 -0.01691253]
R: [-1.23626466 -0.40424685  2.42243547]


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