In [1]:
########################################################################
#
# Copyright (c) 2022, STEREOLABS.
#
# All rights reserved.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
########################################################################
import numpy as np
import pyzed.sl as sl
# import pyzed.core.RESOLUTION

def getIntrinsics(zed_cam_object):
    fx = zed_cam_object.fx
    fy = zed_cam_object.fy
    cx = zed_cam_object.cx
    cy = zed_cam_object.cy
    disto = zed_cam_object.disto
    cam_mtx = np.zeros([3,3])
    cam_mtx[0,0] = fx
    cam_mtx[1,1] = fy
    cam_mtx[0,2] = cx
    cam_mtx[1,2] = cy
    cam_mtx[2,2] = 1
    return cam_mtx, disto

def main():
    # Create a Camera object
    zed = sl.Camera()

    # Create a InitParameters object and set configuration parameters
    init_params = sl.InitParameters(camera_resolution=sl.RESOLUTION.HD1080)
    init_params.sdk_verbose = False

    # Open the camera
    err = zed.open(init_params)
    if err != sl.ERROR_CODE.SUCCESS:
        exit(1)

    # Get camera information (ZED serial number)
    # zed_imu = zed.get_camera_information().camera_imu_transform
    # print('imu transform:',zed_imu.get_orientation().get(), zed_imu.get_translation().get())
    zed_calib_left = zed.get_camera_information().calibration_parameters.left_cam
    # zed_calib_right = zed.get_camera_information().calibration_parameters.right_cam
    zed_calib_stereo = zed.get_camera_information().calibration_parameters.stereo_transform
    zed_calib_R = zed.get_camera_information().calibration_parameters.R
    zed_calib_T = zed.get_camera_information().calibration_parameters.T
    zed_baseline = zed.get_camera_information().calibration_parameters.get_camera_baseline()

    zed_calib_left_raw = zed.get_camera_information().calibration_parameters_raw.left_cam

    l_cam_mtx_raw, l_disto_raw = getIntrinsics(zed_calib_left_raw)
    l_cam_mtx, l_disto = getIntrinsics(zed_calib_left)
    # r_cam_mtx, r_disto = getIntrinsics(zed_calib_right)
    np.save('../params/zed_M_l_t.npy',l_cam_mtx)
    print("Hello! This is my raw intrinsic params left: \n{0}".format(l_cam_mtx_raw))
    print("Hello! This is my rec intrinsic params left: \n{0}".format(l_cam_mtx))
    # print("Hello! This is my intrinsic params right: \n{0}".format(r_cam_mtx))
    print("Hello! This is my stereo trans params left: \n{0}".format(zed_calib_stereo))
    print("Hello! This is my R params right: \n{0}".format(zed_calib_R))
    print("Hello! This is my T params right: \n{0}".format(zed_calib_T))
    print("Hello! This is zed baseline: \n{0}".format(zed_baseline))
    #np.save('imu_eye_transform.npy', zed_imu)

    # Close the camera
    zed.close()

if __name__ == "__main__":
    main()

Hello! This is my raw intrinsic params left: 
[[1.39943005e+03 0.00000000e+00 9.35270020e+02]
 [0.00000000e+00 1.39893994e+03 5.42310974e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Hello! This is my rec intrinsic params left: 
[[1.44665466e+03 0.00000000e+00 9.36044556e+02]
 [0.00000000e+00 1.44665466e+03 5.11092041e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Hello! This is my stereo trans params left: 
51B03E0
1.000000 0.000000 0.000000 63.050861
0.000000 1.000000 0.000000 0.000000
0.000000 0.000000 1.000000 0.000000
0.000000 0.000000 0.000000 1.000000

Hello! This is my R params right: 
[0. 0. 0.]
Hello! This is my T params right: 
[63.05086136  0.          0.        ]
Hello! This is zed baseline: 
63.05086135864258


In [4]:
import numpy as np
mtx = np.load('../params/zed_M_l.npy')
mtx

array([[1.44665466e+03, 0.00000000e+00, 9.36044556e+02],
       [0.00000000e+00, 1.44665466e+03, 5.11092041e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])